"""empty message

Revision ID: 2b7ea7d6f8cf
Revises: 260bb43d973e
Create Date: 2020-08-11 20:17:02.247565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7ea7d6f8cf'
down_revision = '260bb43d973e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity', sa.DateTime(), nullable=False),
    sa.Column('time_left', sa.Integer(), nullable=True),
    sa.Column('input', sa.String(length=200), nullable=True),
    sa.Column('output', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=True))
    op.drop_table('activity')
    # ### end Alembic commands ###
