"""empty message

Revision ID: 44f2b121e8ec
Revises: 9eafb53db476
Create Date: 2020-08-12 13:07:40.324578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f2b121e8ec'
down_revision = '9eafb53db476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('words_left', sa.Integer(), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('activity', 'words_left')
    # ### end Alembic commands ###
