"""empty message

Revision ID: 4dfa1b799564
Revises: ef784e0c2d1f
Create Date: 2020-08-04 14:05:41.491914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfa1b799564'
down_revision = 'ef784e0c2d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
