"""empty message

Revision ID: 6bfd4f6ab0f9
Revises: 44547dbb0e4f
Create Date: 2020-08-12 15:17:11.654020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfd4f6ab0f9'
down_revision = '44547dbb0e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('time', sa.Date(), nullable=False))
    op.drop_column('activity', 'words_left')
    op.drop_column('activity', 'time_left')
    op.add_column('users', sa.Column('subscription_validity', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('time_left', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('words_left', sa.Integer(), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'words_left')
    op.drop_column('users', 'time_left')
    op.drop_column('users', 'subscription_validity')
    op.add_column('activity', sa.Column('time_left', sa.INTEGER(), nullable=True))
    op.add_column('activity', sa.Column('words_left', sa.INTEGER(), nullable=True))
    op.drop_column('activity', 'time')
    # ### end Alembic commands ###
