"""empty message

Revision ID: 9eafb53db476
Revises: 2b7ea7d6f8cf
Create Date: 2020-08-12 13:04:11.085899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eafb53db476'
down_revision = '2b7ea7d6f8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('words_left', sa.Integer(), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('activity', 'words_left')
    # ### end Alembic commands ###
