"""empty message

Revision ID: ef784e0c2d1f
Revises: 0b6e3baf1b6a
Create Date: 2020-08-04 13:57:25.762825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef784e0c2d1f'
down_revision = '0b6e3baf1b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('membership', sa.String(length=50), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'membership')
    # ### end Alembic commands ###
